(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d');let state,db,mode='settings',selected=0,exchange=null,drawVersion=0,saveQueue=Promise.resolve(),timer;
const images=new Map(),MAX=1000000000;
const themes={purple:{accent:'#5546df',background:'#eeecff',complete:'#dcfce7'},blue:{accent:'#1767c4',background:'#e1efff',complete:'#c9f1ea'},pink:{accent:'#bc286b',background:'#ffe5ef',complete:'#ffe8b5'},orange:{accent:'#a94a0a',background:'#fff0d8',complete:'#d6f2cb'}};
const palette=()=>themes[state.theme]||themes.purple;
const blank=()=>({type:'empty',text:'',image:'',price:0,required:1,used:0,done:false});
function giftImage(symbol,color){const c=document.createElement('canvas');c.width=c.height=180;const g=c.getContext('2d');g.fillStyle=color;g.beginPath();g.arc(90,90,82,0,Math.PI*2);g.fill();g.font='100px "Segoe UI Emoji"';g.textAlign='center';g.textBaseline='middle';g.fillText(symbol,90,95);return c.toDataURL('image/png');}
function sample(){const gifts=[['🌹','ローズ',10,10,'#ffe4ec'],['🎁','ギフトBOX',100,5,'#e8e2ff'],['💎','ダイヤ',500,3,'#dff3ff'],['⭐','スター',50,10,'#fff2ce']];const missions=["5人の\n新規フォロワー\n獲得","新規\n★1バッジ\n10人","メータ\n50k\n達成","配信時間\n2時間\n達成","スパラ\n30人\nから貰う","初見さんから\n1,000コイン以上\nのギフト","同接数\n15人\n以上","1人から\n5,000コイン以上\nのギフト"];return{version:1,panels:Array.from({length:25},(_,i)=>{if(i===12)return{...blank(),type:'free'};if(i===24)return blank();if(i%3===1)return{...blank(),type:'mission',text:missions[Math.floor(i/3)%missions.length],done:i===1||i===10};const g=gifts[i%4];return{...blank(),type:'gift',text:'',image:giftImage(g[0],g[4]),price:g[2],required:g[3],used:i===0?10:i===3?7:i%4};})};}
const achieved=p=>p.type==='free'||p.type==='mission'&&p.done||p.type==='gift'&&p.used>=p.required;
function totals(){return state.panels.reduce((a,p)=>{if(p.type==='gift'){a.target+=p.price*p.required;a.used+=p.price*p.used;a.remaining+=p.price*Math.max(0,p.required-p.used);}return a;},{target:0,used:0,remaining:0});}
const fmt=n=>n.toLocaleString('ja-JP');
function cleanState(value){const copy=structuredClone(value);copy.panels.forEach(p=>{if(p.type==='gift')delete p.text;});return copy;}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),3000);}
function write(value){return new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put(value,'board');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function save(){const snapshot=cleanState(state);$('saveStatus').textContent='保存中…';saveQueue=saveQueue.catch(()=>{}).then(()=>write(snapshot)).then(()=>{$('saveStatus').textContent='自動保存済み';}).catch(()=>{$('saveStatus').textContent='保存に失敗';toast('保存できませんでした。バックアップを書き出してください。');});}
function round(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function lines(text,size,width){ctx.font=`700 ${size}px "Yu Gothic UI",Meiryo,sans-serif`;const out=[];let line='';for(const c of Array.from(text)){if(c==='\n'){out.push(line);line='';continue;}if(line&&ctx.measureText(line+c).width>width&&!/[、。，．！？!?)）】」』]/.test(c)){out.push(line);line=c;}else line+=c;}out.push(line);return out;}
function fitted(text,x,y,width,height,max=36,min=1){let size=max,arr;do{arr=lines(text,size,width);if(arr.length*size*1.45<=height)break;size-=1;}while(size>=min);ctx.font=`700 ${Math.max(min,size)}px "Yu Gothic UI",Meiryo,sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';const lineHeight=Math.max(min,size)*1.45;arr.forEach((s,i)=>ctx.fillText(s,x,y+(i-(arr.length-1)/2)*lineHeight,width));}
function loadImage(src){if(!src)return Promise.resolve(null);if(!images.has(src))images.set(src,new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=src;}));return images.get(src);}
async function draw(){const version=++drawVersion;const assets=await Promise.all(state.panels.map(p=>loadImage(p.image)));if(version!==drawVersion)return false;const theme=palette();ctx.fillStyle=theme.background;ctx.fillRect(0,0,1500,1500);for(let i=0;i<25;i++){const p=state.panels[i],x=30+i%5*290,y=30+Math.floor(i/5)*290,w=280;round(x,y,w,w,18,p.type==='free'?theme.accent:achieved(p)?theme.complete:'#ffffff');ctx.fillStyle=p.type==='free'?'#ffffffaa':'#9590b1';ctx.font='600 21px "Yu Gothic UI",Meiryo,sans-serif';ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.fillText(String(i+1).padStart(2,'0'),x+19,y+30);if(p.type==='free'){ctx.fillStyle='#fff';fitted('★',x+140,y+101,220,90,80);fitted('FREE',x+140,y+191,240,70,48);}else if(p.type==='gift'){const img=assets[i];if(img){const scale=Math.min(120/img.width,120/img.height);ctx.drawImage(img,x+140-img.width*scale/2,y+47+(120-img.height*scale)/2,img.width*scale,img.height*scale);}else{ctx.fillStyle='#aaa4c4';fitted('GIFT',x+140,y+108,240,100,32);}ctx.fillStyle='#333044';ctx.fillStyle='#000000';fitted(`${fmt(p.price)} coin`,x+140,y+202,250,58,38);ctx.fillStyle='#d71920';fitted(`${fmt(p.used)} / ${fmt(p.required)}`,x+140,y+251,245,58,38);}else if(p.type==='mission'){ctx.fillStyle='#a097c4';ctx.font='700 18px "Yu Gothic UI",Meiryo,sans-serif';ctx.textAlign='center';ctx.fillText('MISSION',x+140,y+60);ctx.fillStyle='#d71920';fitted(p.text||'ミッション',x+140,y+165,238,172,37);}else{ctx.fillStyle='#c0bacf';/* 未設定パネルは空欄 */}if(achieved(p)&&p.type!=='free'){ctx.save();ctx.translate(x+211,y+67);ctx.rotate(-.2);ctx.fillStyle='#edfff1ee';ctx.strokeStyle='#16834c';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,49,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#16834c';ctx.font='900 22px "Yu Gothic UI",Meiryo,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('達成',0,0);ctx.restore();}}return true;}
function refresh(){$('theme').value=state.theme||'purple';document.documentElement.style.setProperty('--accent',palette().accent);const t=totals();for(const k of ['target','used','remaining'])$(k).textContent=fmt(t[k]);$('settings').classList.toggle('active',mode==='settings');$('progress').classList.toggle('active',mode==='progress');$('selectionLabel').textContent=exchange!==null?'交換先のパネルを選んでください':mode==='settings'?'パネルを選んで編集':'パネルを選んで進捗を更新';document.querySelectorAll('.cell-buttons button').forEach((b,i)=>{b.classList.toggle('selected',i===selected);b.classList.toggle('exchange',i===exchange);const p=state.panels[i];b.setAttribute('aria-label',`パネル${i+1} ${p.type==='free'?'FREE':p.type==='gift'?'ギフト消費':p.text||'未設定'}${achieved(p)?' 達成済み':''}`);});renderEditor();draw();}
function input(label,id,type,value,attrs=''){return `<label>${label}<input id="${id}" type="${type}" ${attrs}></label>`;}
function renderEditor(){const p=state.panels[selected];$('editorTitle').textContent=`パネル ${String(selected+1).padStart(2,'0')}`;$('achievement').textContent=achieved(p)?'達成済み':'';const el=$('editor');if(p.type==='free'){el.innerHTML='<p class="hint">中央は固定のFREEパネルです。最初から達成扱いになります。</p>';return;}if(mode==='settings'){el.innerHTML='<label>パネルの種類<select id="type"><option value="empty">未設定</option><option value="gift">ギフト消費</option><option value="mission">ミッション</option></select></label>'+(p.type==='gift'?'<div class="image-picker"><img id="giftPreview" alt="ギフト画像"><label>ギフト画像<input id="image" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></label></div><div class="two">'+input('単価（コイン）','price','number',p.price,'min="0" max="1000000000" step="1"')+input('必要数','required','number',p.required,'min="1" max="1000000000" step="1"')+'</div>':p.type==='mission'?'<label>ミッション内容<textarea id="text" maxlength="2000"></textarea></label>':'<p class="hint">ギフト消費またはミッションを選んで設定します。</p>')+'<button id="swap">'+(exchange===null?'別のパネルと交換':'交換をキャンセル')+'</button>'; $('type').value=p.type;$('type').onchange=e=>{p.type=e.target.value;changed();};if(p.type==='gift'){$('giftPreview').src=p.image||'';bindNumber('price','price',0);bindNumber('required','required',1);$('image').onchange=upload;}if(p.type==='mission'){$('text').value=p.text;bindText('text','text');}$('swap').onclick=()=>{exchange=exchange===null?selected:null;refresh();};}else{if(p.type==='empty'){el.innerHTML='<p class="hint">未設定です。設定モードで内容を指定してください。</p>';return;}if(p.type==='gift'){el.innerHTML='<p id="giftName" class="hint"></p>'+input('使用数','usedCount','number',p.used,'min="0" max="1000000000" step="1"')+'<div class="actions"><button id="minus">−1</button><button id="plus">＋1</button><button id="plus10">＋10</button></div><p class="hint">必要数に達すると自動で達成になります。使用数は直接入力で訂正できます。</p>';$('giftName').textContent=`必要数 ${fmt(p.required)}`;bindNumber('usedCount','used',0);for(const [id,d]of [['minus',-1],['plus',1],['plus10',10]])$(id).onclick=()=>{p.used=Math.max(0,Math.min(MAX,p.used+d));changed();};}else{el.innerHTML='<p id="missionText" class="hint"></p><button id="done" class="primary"></button>';$('missionText').textContent=p.text;$('done').textContent=p.done?'達成を解除':'ミッション達成';$('done').onclick=()=>{p.done=!p.done;changed();};}}}
function changed(){save();refresh();}
function bindText(id,key){$(id).oninput=e=>{state.panels[selected][key]=e.target.value;save();draw();const t=totals();$('remaining').textContent=fmt(t.remaining);};}
function bindNumber(id,key,min){$(id).value=state.panels[selected][key];$(id).onchange=e=>{const n=Number(e.target.value);if(e.target.value===''||!Number.isSafeInteger(n)||n<min||n>MAX){toast(`${min}〜${MAX}の整数を入力してください`);e.target.value=state.panels[selected][key];return;}state.panels[selected][key]=n;changed();};}
async function upload(e){const file=e.target.files[0],index=selected;if(!file)return;if(file.size>20*1024*1024){toast('20MB以下の画像を選んでください');return;}try{const data=await new Promise((r,j)=>{const reader=new FileReader();reader.onload=()=>r(reader.result);reader.onerror=j;reader.readAsDataURL(file);});const img=await loadImage(data);if(!img)throw Error();const c=document.createElement('canvas'),scale=Math.min(1,800/img.width,800/img.height);c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);state.panels[index].image=c.toDataURL('image/png');changed();}catch{toast('画像を読み込めませんでした');}}
function confirmation(title,text,action){$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('confirm').showModal();$('cancel').onclick=()=>$('confirm').close();$('accept').onclick=()=>{$('confirm').close();action();};}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function pngFilename(now=new Date()){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(now);const values=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `BingoPanel_${values.year}${values.month}${values.day}_${values.hour}${values.minute}${values.second}.png`;}
async function exportPNG(){await draw();return new Promise((r,j)=>canvas.toBlob(b=>b?r(b):j(Error('画像出力に失敗しました')),'image/png'));}
function validate(s){if(!s||s.version!==1||!Array.isArray(s.panels)||s.panels.length!==25)throw Error();return{version:1,theme:Object.hasOwn(themes,s.theme)?s.theme:'purple',panels:s.panels.map((p,i)=>{if(!p||!['empty','gift','mission','free'].includes(p.type)||i===12&&p.type!=='free'||i!==12&&p.type==='free'||p.type!=='gift'&&(typeof p.text!=='string'||p.text.length>2000)||typeof p.image!=='string'||p.image.length>6000000||p.image&&!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(p.image)||typeof p.done!=='boolean')throw Error();for(const k of ['price','used','required'])if(!Number.isSafeInteger(p[k])||p[k]<(k==='required'?1:0)||p[k]>MAX)throw Error();return{type:p.type,...(p.type==='gift'?{}:{text:p.text}),image:p.image,price:p.price,required:p.required,used:p.used,done:p.done};})};}
async function init(){try{db=await new Promise((r,j)=>{const req=indexedDB.open('bingo-studio',1);req.onupgradeneeded=()=>req.result.createObjectStore('data');req.onsuccess=()=>r(req.result);req.onerror=()=>j(req.error);});const stored=await new Promise((r,j)=>{const req=db.transaction('data').objectStore('data').get('board');req.onsuccess=()=>r(req.result);req.onerror=()=>j(req.error);});if(stored){try{state=validate(stored);}catch{state=sample();toast('保存データを読み込めないためサンプルを表示しています');}}else state=sample();$('saveStatus').textContent='自動保存済み';}catch{state=sample();$('saveStatus').textContent='自動保存を利用できません';toast('自動保存を利用できません。バックアップをご利用ください。');}$('theme').onchange=e=>{state.theme=e.target.value;changed();};for(let i=0;i<25;i++){const b=document.createElement('button');b.onclick=()=>{if(exchange!==null){if(i===12){toast('中央FREEは交換できません');return;}if(i!==exchange){[state.panels[i],state.panels[exchange]]=[state.panels[exchange],state.panels[i]];save();}exchange=null;}selected=i;refresh();};$('cells').appendChild(b);}for(const m of ['settings','progress'])$(m).onclick=()=>{mode=m;exchange=null;refresh();};$('export').onclick=async()=>{try{download(await exportPNG(),pngFilename());toast('PNGを保存しました');}catch{toast('PNG出力に失敗しました');}};$('backup').onclick=()=>download(new Blob([JSON.stringify(cleanState(state),null,2)],{type:'application/json'}),'bingo-backup.json');$('restore').onclick=()=>$('backupFile').click();$('backupFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>150*1024*1024){toast('バックアップファイルが大きすぎます');return;}try{const restored=validate(JSON.parse(await file.text()));const loaded=await Promise.all(restored.panels.map(p=>loadImage(p.image)));if(restored.panels.some((p,i)=>p.image&&!loaded[i]))throw Error();confirmation('バックアップを読み込みますか？','現在の画像・設定・進捗を、選んだファイルの内容で置き換えます。',()=>{state=restored;exchange=null;changed();toast('バックアップを読み込みました');});}catch{toast('有効なBINGOバックアップではありません');}};$('restoreDefaults').onclick=()=>confirmation('デフォルト設定に戻しますか？','現在の画像・設定・進捗を、初回サンプルの内容に置き換えます。サンプルの使用数と達成状態も復元し、カラーはパープルに戻ります。残したい内容は先にバックアップを書き出してください。',()=>{state=sample();state.theme='purple';selected=0;exchange=null;changed();toast('デフォルト設定に戻しました');});$('resetSettings').onclick=()=>confirmation('設定をすべてリセットしますか？','ギフト画像・単価・必要数・ミッション・進捗を削除し、中央FREE以外を未設定に戻します。カラーはパープルに戻ります。残したい内容は先にバックアップを書き出してください。',()=>{state={version:1,theme:'purple',panels:Array.from({length:25},(_,i)=>({...blank(),type:i===12?'free':'empty'}))};selected=0;exchange=null;changed();toast('設定をリセットしました');});$('reset').onclick=()=>confirmation('進捗をリセットしますか？','ギフトの使用数とミッションの達成状態を初期化します。画像・設定・中央FREEは保持します。',()=>{state.panels.forEach(p=>{p.used=0;p.done=false;});changed();toast('進捗をリセットしました');});refresh();if(db)save();window.bingo={exportPNG,getState:()=>cleanState(state),totals,validate};}
init().then(()=>{const context=document.modelContext;if(!context?.registerTool)return;try{Promise.resolve(context.registerTool({name:'read_bingo_board',description:'現在のBINGO設定、集計と、盤面のみの1500×1500 PNGを取得します。変更は行いません。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{if(!input||Object.keys(input).length)throw Error('入力は空のオブジェクトにしてください');await draw();return{state:cleanState(state),totals:totals(),png:canvas.toDataURL('image/png')};}})).catch(()=>{});}catch{}});
})();



